# This is a workflow for building the entropy executable on all three major platforms.

name: Build-All-Platforms

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      # Check-out repository
      - uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        
      - name: Install libfuse
        run: sudo apt install -y libfuse2

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: entropy.py
  
      # Uploads artifacts
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
